[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [[redirects]]
  from = "/*"
  to = "/maintenance.html"
  status = 200
  conditions = { Host = "securevibing.com" }