[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["sharp"]

# Configure webhook timeout
[functions."api/webhooks/paddle"]
  timeout = 60  # 1 minute for webhook processing

